

export const locations: string[] = [
    "Angkaew reservoir",
    "Chiang mai university art center",
    "Registration office, chiang mai university",
    "Faculty of science",
    "Faculty of humanities",
    "Faculty of social sciences",
    "Faculty of law",
    "Faculty of political science & public administration",
    "Faculty of economics",
    "Faculty of mass communication",
    "College of arts, media & technology",
    "Faculty of engineering",
    "Faculty of architecture",
    "Faculty of education",
    "Faculty of business administration",
    "Faculty of fine arts",
    "Faculty of agriculture",
    "Faculty of pharmacy",
    "Faculty of dentistry",
    "Faculty of medicine",
    "Maharaj nakorn chiangmai hospital",
    "Faculty of associated medical science",
    "Faculty of nursing",
    "Faculty of public heath",
    "office of the university",
    "information technology service center (itsc)",
    "registration office",
    "main library",
    "language institute",
    "science and techonology research institute",
    "social research institute",
    "research institute for health sciences",
    "graduate school",
    "CMU Central canteen",
    "CMU innovative learnning center",
    "CMU public transportation center",
    "Small animal hospital",
    "The office of student union",
    "CMU staff club",
    "CMU demonstration school",
    "Rom-suk market (kad faihin)",
    "Center for the promotion of arts and culture",
    "CMU alumni relations center",
    "University academic service center",
    "International college of digital innovation",
    "Sala dham",
    "Sala ang-kaew",
    "King's 7th cycle anniversary building",
    "Cmu art museum",
    "Cmu convention hall",
    "Rugby-football field",
    "Rujirawong swimming pool",
    "Main stadium",
    "Gymnasium",
    "Sport field",
    "Hockey field",
    "Football field 2",
    "Softball field",
    "Fitness park",
    "Male dormitories",
    "Female dormitories",
    "Cmu information center",
    "CMU savings & credit cooperative limited"
];